### ISSUE TITLE
Change file extension of converted files.

### ISSUE THREAD

**Issue by itg-dave** [mescedia/mescedia-edi-server#3]
Hello again,

is it possible to change the file extension of converted files? Currently the files are converted correct but will be saved as the original file name including the extension:

filename.edi -> convert via EDIFACT2XML -> filename.edi (now XML)

Would be great if the files are renamed to filename.xml after conversion and vice versa.

Best regards,

Dave

**Comment by mescedia** [comment]
Hi Dave, 

This is part of the [apache-camel file2](http://camel.apache.org/file2.html) component and the [file-language](http://camel.apache.org/file-language.html) which is also part of the  [simple language dsl](http://camel.apache.org/simple.html).
You will have to modify 'deploy/edi-routes.xml' file to achive this goal ...

Change the file-endpoint from this:
`<to uri="file://./CAMEL_FS/EDIFACT_2_XML_OUT"/>`
to this:
`<to uri="file://./CAMEL_FS/EDIFACT_2_XML_OUT?fileName=${file:onlyname.noext}.xml"/>`

MichaelK

**Comment by itg-dave** [comment]
Hi Michael,

thanks for the fast reply! I should do my homework on Camel :D , I'm completely new to this.

Thanks again for your help, worked as intended :)

Dave
